export const homeCopy = {
  ar: {
    eyebrow: "أنظمة وكيلة للأعمال · العربية أولًا", title: "نربط المعرفة بالقرار.", titleAccent: "والقرار بالتنفيذ.", intro: "حوّل إجراءات العمل إلى خطط قابلة للمراجعة. ابدأ بفهم العملية، ثم حدد البيانات والصلاحيات والقرار الذي يبقى بيد فريقك.", primary: "جهّز موجز مشروع", secondary: "جرّب مساحة الوكيل", available: "متاح الآن: تجربة تصميم للقراءة فقط", region: "مصمم لعمليات المؤسسات في مصر والخليج", chips: ["العربية والإنجليزية", "مراجعة الافتراضات", "بدون إجراءات خارجية"],
    featuresLabel: "01 / المنصة", featuresTitle: "العملية أولًا. التقنية في خدمتها.", featuresIntro: "ابدأ بما يحتاجه فريقك فعلًا، من معلومة ناقصة إلى قرار يمكن مراجعته.", features: [
      ["فهم قبل التنفيذ", "حدد الهدف وصاحب العملية والمدخلات. عند نقص المعلومات، تبدأ الخطة بالأسئلة الصحيحة."],
      ["خطة يمكن مناقشتها", "اربط كل خطوة ببياناتها وصلاحياتها والمخرج المطلوب، بدل ترك القرار داخل محادثة طويلة."],
      ["نتيجة تحت المراجعة", "راجع الافتراضات والاستثناءات ومعيار القبول. لا تتحول المسودة تلقائيًا إلى فعل خارجي."],
    ],
    processLabel: "02 / منهج العمل", processTitle: "من مشكلة يومية إلى مسار واضح.", processIntro: "الربط يأتي بعد فهم العملية واختبارها، وليس قبل تحديد مسؤوليتها.", steps: [["حدد", "عملية واحدة، مالك قرار، ونتيجة قابلة للتحقق."], ["صمم", "مدخلات وخطوات واستثناءات وحدود صلاحيات."], ["راجع", "عينة افتراضية، افتراضات ظاهرة، ومعايير قبول."], ["اربط تدريجيًا", "بعد تنفيذ الهوية والصلاحيات والتحقق من الأثر."]],
    solutionsLabel: "03 / حالات الاستخدام", solutionsTitle: "ابدأ من العمل الذي يتكرر.", solutionsIntro: "أمثلة لعمليات يمكن دراستها وتصميمها. ليست تكاملات جاهزة أو نتائج عملاء.", explore: "استكشف حالات الاستخدام", useCases: [["المشتريات", "من طلب غير مكتمل إلى ملف واضح للمراجع.", "طلب ← استكمال ← مراجعة"], ["المالية", "من سجل فواتير إلى مسودة متابعة تحت الاعتماد.", "فواتير ← استثناءات ← مسودة"], ["المعرفة الداخلية", "من سؤال موظف إلى خطة مصادر وتصعيد عند الشك.", "سؤال ← مصدر ← مراجعة"]],
    controlsLabel: "04 / الضوابط", controlsTitle: "الحدود جزء من التصميم.", controlsIntro: "نعرض ما يعمل اليوم بوضوح، ونفصل عنه ما يحتاج تطويرًا وتفويضًا قبل الاستخدام المؤسسي.", now: "متاح في التجربة", later: "مراحل التطوير التالية", current: ["تصميم عملية ومراجعة افتراضاتها", "حساب خط الأساس من أرقامك", "مراجع تقنية مختارة وتنزيل المحادثة"], roadmap: ["هوية مؤسسية وصلاحيات معزولة", "حفظ دائم واستئناف وموافقات موثقة", "موصلات أنظمة بإذن ونطاق محدد"], controlsLink: "اقرأ ضوابط التشغيل", resourcesLabel: "05 / ابدأ بوضوح", resourcesTitle: "الموجز الجيد يجعل الخطوة التالية أسهل.", resourcesIntro: "حدد المشكلة والبيانات وصاحب القرار، وراجع الموجز داخل المتصفح. لا يُرسل إلى فريق أو نظام.", resourcesLink: "راجع أدلة القبول", cta: "ما العملية التي تريد تحسينها؟", ctaIntro: "ابدأ بمثال افتراضي في مساحة الوكيل، أو جهّز موجزًا يناقشه فريقك.", exampleNotice: "استخدم بيانات افتراضية فقط. لا تضف أسرارًا أو بيانات عملاء.",
  },
  en: {
    eyebrow: "Agents for business · Arabic first", title: "Connect knowledge to decisions.", titleAccent: "And decisions to action.", intro: "Turn business processes into reviewable plans. Understand the workflow, define the data and permissions, and keep consequential decisions with your team.", primary: "Prepare a project brief", secondary: "Try the agent workspace", available: "Available now: a read-only design preview", region: "Designed for enterprise workflows in Egypt and the Gulf", chips: ["Arabic and English", "Reviewed assumptions", "No external actions"],
    featuresLabel: "01 / Platform", featuresTitle: "The process first. Technology follows.", featuresIntro: "Start with what your team needs, from missing information to a decision that can be reviewed.", features: [
      ["Understand before acting", "Define the goal, process owner, and inputs. When information is missing, the plan begins with the right questions."],
      ["A plan you can discuss", "Connect every step to its data, permissions, and expected output, instead of burying decisions in a long conversation."],
      ["Keep the result reviewable", "Check assumptions, exceptions, and acceptance criteria. A draft does not automatically become an external action."],
    ],
    processLabel: "02 / Our process", processTitle: "From a daily problem to a clear workflow.", processIntro: "Connect systems after understanding and testing the process, with an explicit owner.", steps: [["Define", "One process, a decision owner, and a verifiable outcome."], ["Design", "Inputs, steps, exceptions, and permission boundaries."], ["Review", "Fictional cases, visible assumptions, and acceptance criteria."], ["Connect gradually", "After identity, permissions, and effect verification are implemented."]],
    solutionsLabel: "03 / Use cases", solutionsTitle: "Start with the work that repeats.", solutionsIntro: "Examples of workflows to explore and design. These are not ready-made integrations or customer results.", explore: "Explore use cases", useCases: [["Procurement", "From an incomplete request to a clear review packet.", "Request → complete → review"], ["Finance", "From invoice records to a follow-up draft for approval.", "Invoices → exceptions → draft"], ["Internal knowledge", "From employee questions to source planning and escalation.", "Question → source → review"]],
    controlsLabel: "04 / Controls", controlsTitle: "Boundaries are part of the design.", controlsIntro: "See what works today, alongside what needs development and authorization before enterprise use.", now: "Available in the preview", later: "Next development stages", current: ["Workflow design and assumption review", "Baseline calculations from your figures", "Selected technical references and chat download"], roadmap: ["Enterprise identity and isolated permissions", "Durable execution and persisted approvals", "Authorized connections with scoped access"], controlsLink: "Read operating controls", resourcesLabel: "05 / Start clearly", resourcesTitle: "A good brief makes the next step easier.", resourcesIntro: "Define the problem, data, and decision owner, then review a brief in your browser. Nothing is sent to a team or system.", resourcesLink: "Review acceptance guides", cta: "Which workflow would you improve?", ctaIntro: "Start with a fictional example in the agent workspace, or prepare a brief for your team to discuss.", exampleNotice: "Use fictional data only. Do not enter secrets or customer records.",
  },
} as const;
