import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { isLocale } from '@/lib/i18n/config';
import { PageHeader } from '@/components/site/page-header';
import { FooterSection } from '@/components/landing/footer-section';
import { ImpactEstimator } from '@/components/site/impact-estimator';
type Props={params:Promise<{locale:string}>};
const rows={ar:[['زمن العمل النشط','وقت الموظف في تنفيذ الحالة؛ يُفصل عن انتظار المورد أو المدير.'],['زمن الدورة','من وصول الطلب إلى اكتماله، ببداية ونهاية موحدتين.'],['اكتمال الملف','وجود البيانات والمستندات اللازمة وفق قائمة متفق عليها.'],['إعادة العمل','التصحيح وإعادة التقديم؛ يُفصل خطأ النظام عن نقص المدخلات.'],['جودة النتيجة','صحة الحقول والمراجع والقرار الإجرائي وفق عينة مراجعة.'],['تكلفة الحالة المكتملة','النموذج والأدوات والتخزين والمراجعة، بما يشمل المحاولات الفاشلة.'],['الاعتماد التشغيلي','الاستخدام اليومي، والتوقف والاستثناءات والدعم.']],en:[['Active work time','Staff time per case, separated from waiting for a supplier or manager.'],['Cycle time','From arrival to completion, with consistent start and end points.'],['File completeness','Required data and documents against an agreed checklist.'],['Rework','Correction and resubmission, distinguishing system error from missing inputs.'],['Outcome quality','Field, citation and procedural accuracy against a review sample.'],['Cost per completed case','Model, tools, storage and review, including unsuccessful attempts.'],['Operational adoption','Daily use, downtime, exceptions and support.']]};
export async function generateMetadata({params}:Props):Promise<Metadata>{const {locale}=await params;return {title:(locale==='ar'?'الجدوى وقياس الأثر':'Feasibility and impact measurement')+' | AgentNexos',alternates:{canonical:`/${locale}/roi`,languages:{ar:'/ar/roi',en:'/en/roi'}}};}
export default async function Page({params}:Props){const {locale}=await params;if(!isLocale(locale))notFound();const ar=locale==='ar';return <div className="min-h-screen bg-background"><PageHeader/><main id="main-content" tabIndex={-1} className="site-section"><p className="text-sm text-primary">{ar?'الجدوى وقياس الأثر':'Feasibility and impact'}</p><h1 className="mt-5 max-w-4xl text-3xl font-semibold leading-snug sm:text-5xl">{ar?'افهم تكلفة الحالة قبل أن تحكم على قيمة الأتمتة.':'Understand the cost of a case before judging automation value.'}</h1><p className="mt-6 max-w-3xl text-lg leading-9 text-muted-foreground">{ar?'ابدأ بالحجم وزمن العمل النشط وإعادة العمل والانتظار. ثم راجع تكلفة التطوير والتشغيل والمتابعة وتحديث المصادر. قارن تجربة محددة بخط أساس مقاس.':'Start with volume, active work, rework and waiting. Include development, operations, monitoring and source updates. Compare a bounded pilot with a measured baseline.'}</p><dl className="mt-12 divide-y divide-border border-y border-border">{rows[locale].map(([name,detail])=><div key={name} className="grid gap-3 py-6 sm:grid-cols-[1fr_2fr]"><dt className="font-medium">{name}</dt><dd className="text-sm leading-8 text-muted-foreground">{detail}</dd></div>)}</dl><ImpactEstimator locale={locale}/><Link href={`/${locale}/start`} className="mt-8 inline-flex rounded-lg bg-primary px-6 py-3 text-sm font-medium text-primary-foreground">{ar?'جهّز موجز العملية':'Prepare a process brief'}</Link></main><div id="site-footer"><FooterSection/></div></div>;}
