import Link from 'next/link';
import { ArrowUpRight } from 'lucide-react';
import { PageHeader } from './page-header';
import { FooterSection } from '@/components/landing/footer-section';
import { catalogs,catalogLabels,type CatalogKind } from '@/lib/content/catalog';
import type { Locale } from '@/lib/i18n/config';
export function CatalogPage({kind,locale,slug}:{kind:CatalogKind;locale:Locale;slug?:string}) {
 const ar=locale==='ar',label=catalogLabels[locale][kind];
 const entry=slug?catalogs[kind].find(x=>x.slug===slug):undefined;
 const c=entry?.[locale];
 const title=c?.title||(kind==='solutions'?(ar?'حلول تبدأ من العمل الذي يحتاج تحسينًا.':'Solutions start with the work that needs improving.'):kind==='industries'?(ar?'نفس منهج البناء. سياق مختلف لكل قطاع.':'One engineering approach. Different operating contexts.'):ar?'معرفة تساعدك على تقييم القرار التقني والتجاري.':'Knowledge for better technical and business decisions.');
 return <div className="min-h-screen bg-background text-foreground"><PageHeader/><main id="main-content" tabIndex={-1} className="site-section">
  <nav aria-label={ar?'مسار الصفحة':'Breadcrumb'} className="mb-10 flex flex-wrap gap-3 text-sm text-muted-foreground"><Link href={`/${locale}`}>{ar?'الرئيسية':'Home'}</Link><span>/</span><Link href={`/${locale}/${kind}`}>{label}</Link>{c&&<><span>/</span><span aria-current="page">{c.title}</span></>}</nav>
  <div className="max-w-4xl"><p className="text-sm font-medium text-primary">AgentNexos / {label}</p><h1 className="mt-5 text-3xl font-semibold leading-snug tracking-tight sm:text-5xl">{title}</h1><p className="mt-6 max-w-3xl text-lg leading-9 text-muted-foreground">{c?.paragraphs[0]||(kind==='resources'?(ar?'أدلة عملية لأصحاب القرار وفرق التنفيذ. ابدأ بالعملية والبيانات والمسؤولية قبل اختيار الأدوات.':'Practical guides for decision owners and delivery teams. Start with process, data and accountability before choosing tools.'):ar?'اختر عملية واحدة لها مدخلات معروفة ومسؤول واضح ونتيجة يمكن التحقق منها. هنا نعرض نطاقات مقترحة تُصمم وتُختبر وفق بيئة كل مؤسسة.':'Choose one process with known inputs, an accountable owner and a verifiable outcome. These proposed scopes are designed and tested for each organization.')}</p></div>
  {kind!=='resources'&&<p className="mt-10 max-w-4xl rounded-xl border-s-2 border-primary bg-card p-5 text-sm leading-7 text-muted-foreground">{ar?'نطاق تصميم وتطوير مقترح؛ ليست هذه موصلات جاهزة أو نتائج عملاء. مساحة الوكيل الحالية تساعد في التصميم والمراجعة، ولا تنفذ هذه العمليات في أنظمتك.':'Proposed design and development scope, rather than ready-made connectors or customer results. The current workspace supports design and review; it does not execute these processes in your systems.'}</p>}
  {c?<article className="mt-14 grid gap-12 lg:grid-cols-[minmax(0,1fr)_260px]"><div className="max-w-3xl space-y-7 text-base leading-9 sm:text-lg">{c.paragraphs.slice(1).map((p,i)=><p key={i} className={/^(مؤشرات|القياس|سيناريو|الأنظمة|ما يظل|نطاق|ما يلزم|Evaluation:|Starting scenario:|Reference systems:|Human responsibility:|Initial scope:|Inputs required:)/.test(p)?'rounded-xl border border-border bg-card p-5 text-base':'text-foreground/85'}>{p.replace(/\s*\[م\d+\]/g,'')}</p>)}</div><aside className="h-fit rounded-2xl border border-border bg-card p-6"><h2 className="font-semibold">{ar?'ابدأ بسؤال واضح':'Start with a clear question'}</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">{ar?'من يملك العملية؟ أين توجد البيانات؟ وما الدليل الذي يثبت تحسن النتيجة؟':'Who owns the process? Where is the data? What evidence would show an improved outcome?'}</p><Link href={`/${locale}/start`} className="mt-6 flex min-h-12 items-center justify-between gap-4 rounded-lg bg-primary px-4 text-sm font-medium text-primary-foreground">{ar?'جهّز موجز المشروع':'Prepare a project brief'}<ArrowUpRight className="size-4 rtl:-scale-x-100"/></Link></aside></article>:<div className="mt-16 divide-y divide-border border-y border-border">{catalogs[kind].map((x,i)=><Link key={x.slug} href={`/${locale}/${kind}/${x.slug}`} className="group grid gap-4 py-8 md:grid-cols-[60px_1fr_1fr_30px]"><span className="font-mono text-sm text-primary">{String(i+1).padStart(2,'0')}</span><h2 className="text-xl font-semibold leading-8 group-hover:text-primary">{x[locale].title}</h2><p className="text-base leading-8 text-muted-foreground">{x[locale].paragraphs[0]}</p><ArrowUpRight className="size-5 rtl:-scale-x-100"/></Link>)}</div>}
  <div className="mt-16 flex flex-wrap gap-5 border-t border-border pt-8">{Object.keys(catalogs).filter(k=>k!==kind).map(k=><Link key={k} href={`/${locale}/${k}`} className="text-sm text-primary hover:underline">{catalogLabels[locale][k as CatalogKind]}</Link>)}<Link href={`/${locale}/security`} className="text-sm text-primary hover:underline">{ar?'الثقة والحوكمة':'Trust and governance'}</Link></div>
 </main><div id="site-footer"><FooterSection/></div></div>;
}
