import Link from 'next/link';
import content from '@/lib/content/editorial-pages.json';
import type { Locale } from '@/lib/i18n/config';
import { PageHeader } from './page-header';
import { FooterSection } from '@/components/landing/footer-section';
export function EditorialPage({page,locale}:{page:keyof typeof content;locale:Locale}){
 const ar=locale==='ar',c=content[page][locale];
 return <div className="min-h-screen bg-background"><PageHeader/><main id="main-content" tabIndex={-1} className="site-section"><Link href={`/${locale}`} className="text-sm text-primary hover:underline">{ar?'الرئيسية':'Home'}</Link><div className="mt-12 grid gap-10 lg:grid-cols-[1fr_2fr]"><div><p className="text-sm text-primary">AgentNexos / {ar?'هندسة أنظمة الأعمال':'Business systems engineering'}</p><h1 className="mt-5 text-3xl font-semibold leading-snug sm:text-4xl">{c.title}</h1><div className="mt-8 rounded-xl border border-border bg-card p-5 font-mono text-sm leading-8 text-muted-foreground" dir="ltr">Intent → Context<br/>Policy → Tools<br/>Review → Evidence</div></div><article className="max-w-3xl space-y-6 text-base leading-9 text-muted-foreground">{page!=='about'&&<p className="mb-8 rounded-xl border-s-2 border-primary bg-card p-5 text-sm leading-8">{ar?'منهج مقترح لتطوير مشاريع المؤسسات. تختلف القدرات المنفذة في مساحة التصميم الحالية؛ لا تعني هذه الصفحة وجود موصلات أو موافقات تشغيلية جاهزة.':'A proposed approach to enterprise project delivery. Implemented design-preview capabilities differ; this page does not imply ready-made connectors or operational approvals.'}</p>}{c.paragraphs.map((p,i)=>p.length<75&&!p.endsWith('.')?<h2 key={i} className="pt-6 text-xl font-semibold text-foreground">{p}</h2>:<p key={i}>{p}</p>)}</article></div><div className="mt-16 flex flex-wrap gap-5 border-t border-border pt-8"><Link href={`/${locale}/start`} className="rounded-lg bg-primary px-6 py-3 text-sm font-medium text-primary-foreground">{ar?'جهّز موجز المشروع':'Prepare a project brief'}</Link><Link href={`/${locale}/roi`} className="rounded-lg border border-border px-6 py-3 text-sm">{ar?'راجع قياس الأثر':'Explore impact measurement'}</Link></div></main><div id="site-footer"><FooterSection/></div></div>;
}
