"use client";

import { useState } from "react";
import Link from "next/link";
import { briefFields, reviewBrief, quoteBriefValue, type BriefField } from "@/lib/project-brief";
import type { Locale } from "@/lib/i18n/config";

const labels: Record<Locale, Record<BriefField | "volume" | "minutes" | "effect", string>> = {
  ar: { goal: "ما المشكلة التي تريد حلها؟", owner: "من يملك العملية والقرار؟", trigger: "ما الطلب الذي يبدأ العملية؟", source: "ما مصدر البيانات المعتمد؟", outcome: "ما المخرج المطلوب؟", acceptance: "كيف تتحقق من نجاح المخرج؟", failure: "ماذا يحدث عند نقص البيانات أو فشل خطوة؟", volume: "عدد الحالات في الشهر (اختياري)", minutes: "الوقت الحالي لكل حالة بالدقائق (اختياري)", effect: "أعلى صلاحية قد تحتاجها العملية" },
  en: { goal: "What problem needs solving?", owner: "Who owns the process and decisions?", trigger: "What request starts the process?", source: "What is the authorized source of truth?", outcome: "What output is needed?", acceptance: "How will you verify a successful output?", failure: "What happens when data is missing or a step fails?", volume: "Cases per month (optional)", minutes: "Current minutes per case (optional)", effect: "Highest permission the process may need" },
};
const initial = { goal: "", owner: "", trigger: "", source: "", outcome: "", acceptance: "", failure: "", volume: "", minutes: "", effect: "draft" };
const effects = ["read", "draft", "external_write", "financial", "delete"] as const;
const effectLabels = { ar: ["قراءة فقط", "مسودات للمراجعة", "إرسال أو تعديل نظام خارجي", "قرار أو إجراء مالي", "حذف بيانات"], en: ["Read only", "Drafts for review", "Send or change an external system", "Financial action", "Delete data"] };
export function ProjectBriefForm({ locale }: { locale: Locale }) {
  const ar = locale === "ar";
  const [values, setValues] = useState(initial);
  const [errors, setErrors] = useState<string[]>([]);
  const [result, setResult] = useState<ReturnType<typeof reviewBrief> | null>(null);
  const [downloaded, setDownloaded] = useState(false);
  const change = (key: string, value: string) => { setValues(previous => ({ ...previous, [key]: value })); setResult(null); setDownloaded(false); setErrors(previous => previous.filter(field => field !== key)); };
  const control = "w-full rounded-xl border border-border bg-background p-3 text-base text-foreground focus-visible:outline-2 focus-visible:outline-offset-4";
  function download() {
    if (!result?.ok) return;
    const b = result.brief;
    const lines = [ar ? "# موجز عملية — للمراجعة" : "# Workflow brief — for review", ar ? "هذا تصميم مبدئي. لا يمنح صلاحيات أو يبدأ تشغيلًا." : "A preliminary design. It grants no permissions and starts no execution.", ...briefFields.flatMap(key => [`## ${labels[locale][key]}`, quoteBriefValue(b[key])]), `## ${labels[locale].effect}`, effectLabels[locale][effects.indexOf(b.effect)], ar ? `يتطلب اعتمادًا بشريًا للفعل الخارجي: ${result.approvalRequired ? "نعم" : "لا؛ أي ربط لاحق يحتاج تفويضًا مستقلًا"}` : `External action approval required: ${result.approvalRequired ? "Yes" : "No; any future integration requires separate authorization"}`, ar ? `خط الأساس: ${result.baselineMinutes === null ? "غير متاح" : result.baselineMinutes + " دقيقة عمل شهريًا"}. ليس تقدير توفير.` : `Baseline: ${result.baselineMinutes === null ? "Unavailable" : result.baselineMinutes + " working minutes per month"}. Not estimated savings.`];
    const url = URL.createObjectURL(new Blob([lines.join("\n\n")], { type: "text/markdown;charset=utf-8" }));
    const anchor = document.createElement("a"); anchor.href = url; anchor.download = `agentnexos-brief-${locale}.md`; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); setDownloaded(true);
  }
  return <form noValidate className="mt-10 flex flex-col gap-8 rounded-2xl border border-border bg-card p-5 sm:p-8" onSubmit={event => { event.preventDefault(); const reviewed = reviewBrief(values); setResult(reviewed); setErrors(reviewed.ok ? [] : reviewed.fields); if (!reviewed.ok) document.getElementById(`brief-${reviewed.fields[0]}`)?.focus(); }}>
    <div className="grid gap-6 md:grid-cols-2">{briefFields.map(key => <div key={key} className={key === "goal" ? "md:col-span-2" : ""}>
      <label className="mb-2 block text-sm leading-7" htmlFor={`brief-${key}`}>{labels[locale][key]}</label>
      <textarea id={`brief-${key}`} required rows={3} maxLength={1200} value={values[key]} onChange={event => change(key, event.target.value)} className={control} aria-invalid={errors.includes(key)} aria-describedby={errors.includes(key) ? `error-${key}` : undefined} />
      {errors.includes(key) && <p id={`error-${key}`} className="mt-2 text-sm text-primary">{ar ? "أضف وصفًا واضحًا من 3 أحرف على الأقل." : "Add a clear description of at least 3 characters."}</p>}
    </div>)}</div>
    <div><label className="mb-2 block text-sm" htmlFor="brief-effect">{labels[locale].effect}</label><select id="brief-effect" className={control} value={values.effect} onChange={event => change("effect", event.target.value)}>{effects.map((effect, index) => <option key={effect} value={effect}>{effectLabels[locale][index]}</option>)}</select></div>
    <div className="grid gap-6 md:grid-cols-2">{(["volume", "minutes"] as const).map(key => <div key={key}><label className="mb-2 block text-sm" htmlFor={`brief-${key}`}>{labels[locale][key]}</label><input id={`brief-${key}`} inputMode="decimal" dir="ltr" maxLength={20} className={control} value={values[key]} onChange={event => change(key, event.target.value)} aria-invalid={errors.includes(key)} aria-describedby={errors.includes(key) ? `error-${key}` : undefined} />{errors.includes(key) && <p id={`error-${key}`} className="mt-2 text-sm text-primary">{ar ? "استخدم رقمًا موجبًا حتى مليون بالأرقام 0–9، أو اتركه فارغًا." : "Use a positive number up to one million with 0–9 digits, or leave blank."}</p>}</div>)}</div>
    <div className="flex flex-wrap gap-4"><button type="submit" className="rounded-xl bg-primary px-6 py-3 text-primary-foreground focus-visible:outline-2 focus-visible:outline-offset-4">{ar ? "راجع موجز العملية" : "Review workflow brief"}</button><button type="button" className="rounded-xl border border-border px-6 py-3 focus-visible:outline-2 focus-visible:outline-offset-4" onClick={() => { setValues(initial); setResult(null); setErrors([]); setDownloaded(false); }}>{ar ? "امسح البيانات" : "Clear details"}</button></div>
    <div aria-live="polite" aria-atomic="true">{result && !result.ok && <p>{ar ? "الموجز يحتاج استكمال الحقول المحددة." : "Complete the indicated fields before review."}</p>}{result?.ok && <section className="space-y-4 rounded-2xl border border-border bg-card/50 p-6"><h2 className="text-xl font-semibold">{ar ? "موجز جاهز للمناقشة" : "Brief ready for discussion"}</h2><p className="leading-8 text-foreground/75">{result.approvalRequired ? (ar ? "العملية تتضمن فعلًا حساسًا. حدد صاحب الاعتماد والتحقق من الأثر قبل الربط؛ لا ينفذ هذا النموذج أي فعل." : "The process includes a sensitive action. Define approval ownership and effect verification before integration; this form performs no action.") : (ar ? "ابدأ بعينة افتراضية واختبارات قبول. ربط بيانات المؤسسة يحتاج تفويضًا مستقلًا." : "Start with fictional cases and acceptance tests. Enterprise data connections require separate authorization.")}</p><p>{ar ? "خط الأساس الحالي: " : "Current baseline: "}{result.baselineMinutes === null ? (ar ? "غير متاح دون حجم ووقت للحالات." : "Unavailable without case volume and time.") : `${result.baselineMinutes.toLocaleString(locale)} ${ar ? "دقيقة عمل شهريًا؛ ليس تقدير توفير." : "working minutes per month; not estimated savings."}`}</p><button type="button" onClick={download} className="rounded-xl border border-border px-5 py-3 focus-visible:outline-2 focus-visible:outline-offset-4">{ar ? "نزّل الموجز بصيغة Markdown" : "Download Markdown brief"}</button><p className="text-sm text-foreground/70">{downloaded ? (ar ? "جهّز المتصفح ملف التنزيل؛ راجع الموجز قبل مشاركته." : "Your browser prepared the download; review it before sharing.") : (ar ? "يبقى الموجز في هذه الصفحة حتى تمسحه أو تغلقها. لم يُرسل إلى فريق أو نظام." : "The brief stays on this page until cleared or closed. It has not been sent to a team or system.")}</p><Link href={`/${locale}/process`} className="inline-block underline underline-offset-4">{ar ? "راجع منهج التسليم والقبول" : "Review delivery and acceptance"}</Link></section>}</div>
  </form>;
}
